# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d8894edfd3f32f9a76240ee87f41ea9fc3b43ed02eed7933117979b89b94c7fc3b491f5b91b101f959f9e990c2536e52778a9b18dfdb8e439f882297e1470ca

test:
  secret_key_base: 44e4a7ff3103578bcd8cc67929f378626d49bcd516431b395374e680ce85080113b3017c372d497335e361d076aa10e4fdd921d2e21565e8c691461f9ea62525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
